### ISSUE TITLE
Problem with self-signed certificates

### ISSUE THREAD

**Issue by andreas-bulling** [worksasintended/overleaf_ldap#3]
Hi,

I ran into the following problem that I noticed when inspecting web.log. Any idea for how to fix this?

```
{"name":"web","hostname":"6544478a031a","pid":414,"level":30,"rss":"115.47","heapTotal":"73.39","heapUsed":"63.50","external":"34.20","msg":"process.memoryUsage()","time":"2020-04-08T22:17:37.057Z","v":0}
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)

Emitted 'error' event at:
    at Backoff.<anonymous> (/node_modules/ldapjs/lib/client/client.js:1228:12)
    at Backoff.emit (events.js:198:13)
    at Backoff.EventEmitter.emit (domain.js:448:20)
    at Backoff.backoff (/node_modules/backoff/lib/backoff.js:41:14)
    at /node_modules/ldapjs/lib/client/client.js:1214:15
    at f (/node_modules/once/once.js:25:25)
    at TLSSocket.onResult (/node_modules/ldapjs/lib/client/client.js:1016:7)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by andreas-bulling** [comment]
Found a workaround - not nice but works. Modify `AuthenticationManager.js`

```
    ldapAuth(query, passwd, onSuccess, callback, adminMail, userObj) {
        tlsOptions = { 'rejectUnauthorized': false }
        const client = ldap.createClient({
            url: process.env.LDAP_SERVER,
            tlsOptions: tlsOptions
        });
```
